// Navigation 
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const TOGGLE_HEADER_SETTING = 'TOGGLE_HEADER_SETTING';
export const CHANGE_HEADER_USERNAME = 'CHANGE_HEADER_USERNAME';

// Authentication 
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// User 
export const FETCH_MY_INFO = 'FETCH_MY_INFO';

// Type 
export const CREATE_TYPE = 'CREATE_TYPE';
export const FETCH_TYPES = 'FETCH_TYPES';
export const DELETE_TYPE = 'DELETE_TYPE';

// Blog 
export const CHANGE_TYPE_NAME = 'CHANGE_TYPE_NAME';
export const CREATE_BLOG_TYPE_SUCCESS = 'CREATE_BLOG_TYPE_SUCCESS';
export const FETCH_BLOG_TYPES_SUCCESS = 'FETCH_BLOG_TYPES_SUCCESS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';

// Vocab 
export const SELECT_PARENT_CATEGORY = 'SELECT_PARENT_CATEGORY';
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';
export const TOGGLE_READY = 'TOGGLE_READY';
export const TOGGLE_SHOW_MODAL = 'TOGGLE_SHOW_MODAL';
export const CHANGE_VOCAB_WORD = 'CHANGE_VOCAB_WORD';
export const CHANGE_VOCAB_DESC = 'CHANGE_VOCAB_DESC';
export const FETCH_VOCAB = 'FETCH_VOCAB';
export const CREATE_VOCAB = 'CREATE_VOCAB';

// Error 
export const API_FAILED = 'API_FAILED';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';